config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :salaries

  root 'salaries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salary.rb
class Salary < ApplicationRecord
  PAYMENT_DAYS = [5, 15, 20]

  belongs_to :user
  validates :user_id, presence: true
  before_save :set_dates

  def self.min_start_date
    Salary.order(starts_at: :asc).first.starts_at
  end

  def self.max_end_date
    Salary.order(ends_at: :asc).last.ends_at
  end

  private

  def last_payment
    Salary.order(:created_at).last
  end

  def set_dates
    self.starts_at = get_starts_at
    self.ends_at = get_ends_at(self.starts_at)
  end

  def get_starts_at
    last = last_payment
    return last.ends_at.tomorrow if last

    get_nearest_date(Date.today)
  end

  def get_ends_at(date)
    get_nearest_date(date.tomorrow).yesterday
  end

  def get_nearest_date(date_from)
    [date_from, date_from.at_beginning_of_month.next_month].each do |date|
      result = PAYMENT_DAYS.map { |d| date.change(day: d) }.detect { |d| date <= d }
      return result unless result.blank?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  has_many :salaries
  validates :username, format: { with: /^[a-zA-Z0-9_\.]*$/, multiline: true }, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :recoverable, :trackable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :authenticate_user!

  def index
    @salaries = Salary.order(ends_at: :asc).page params[:page]
  end

  def new
    current_user.salaries.build.save
    redirect_back(fallback_location: root_path, notice: 'Payment successfully created')
  end

  def destroy
    salary = Salary.find(params[:id])
    salary.destroy if current_user == salary.user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
  def format_date(date)
    date.strftime('%b %d, %Y')
  end
end

app/views/layouts/application.html.haml
%hml
  %head
    %title Payments
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    - if user_signed_in?
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            = link_to 'Application', root_path, class: 'navbar-brand'
          %ul.nav.navbar-nav
            %li= link_to 'Main page', root_path
            %li= link_to 'Payments', root_path
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Logout (#{current_user.email})", destroy_user_session_path, method: :delete

    .container
      .row
        .col-lg-12
          - if notice || alert
            .alert.alert-info= notice || alert
        = yield

app/views/salaries/index.html.haml
.row
  .col-sm-10
    %h4
      = "Payments from #{format_date Salary.min_start_date} to #{format_date Salary.max_end_date}" if @salaries.count > 0
  .col-sm-2
    = link_to 'Add Payment', new_salary_path, class: 'btn submit-btn'
  .col-sm-12
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Dates
          %th Creator
          %th Actions
      %tbody
        - @salaries.each do |salary|
          %tr
            %td= salary.id
            %td= "#{format_date salary.starts_at} - #{format_date salary.ends_at}"
            %td= salary.user.email
            %td
              - if salary.user == current_user
                %button.btn.btn-danger.salary-delete{ data: {salary: salary.id}} Delete

  .col-sm-12
    = paginate @salaries


  .modal.fade#delete-confirmation
    .modal-dialog
      .modal-content
        .modal-header
          %button.close
            %span &times;
          %h4.modal-title Are you sure?

        .modal-body
          %p Are you really want to delete this record?
        .modal-footer
          %a.btn.btn-default{ data: { dissmiss: 'modal' } } Cancel
          %a.btn.btn-danger#confirmation-button{ data: {method: 'delete'} } Delete